title: slides
baseurl: "/slides"
url: "http://xxbc.github.io/slides-test"

collections:
  slides:
    output: true
    permalink: /:path

defaults:
  -
    scope:
      path: ""
      type: "slides"
    values:
      layout: "slides"
